-- Additional persistent cooldown columns used by RPG actions.
ALTER TABLE economy ADD COLUMN IF NOT EXISTS last_rob TIMESTAMPTZ;
ALTER TABLE economy ADD COLUMN IF NOT EXISTS last_hunt TIMESTAMPTZ;
ALTER TABLE economy ADD COLUMN IF NOT EXISTS last_weekly TIMESTAMPTZ;
ALTER TABLE economy ADD COLUMN IF NOT EXISTS last_adventure TIMESTAMPTZ;
ALTER TABLE economy ADD COLUMN IF NOT EXISTS last_fish TIMESTAMPTZ;
ALTER TABLE economy ADD COLUMN IF NOT EXISTS last_mine TIMESTAMPTZ;
