import { register } from '../../Tanu/handlers/commands.js'; import { ensureUser, rpgAvailable, saveUser } from './store.js';
const unavailable = async (ctx: any) => { await ctx.sock.sendMessage(ctx.chat, { text: 'RPG database is not configured or currently unavailable.' }); };
const numeric = (value: string | undefined) => { const amount = Number(value); return Number.isSafeInteger(amount) && amount > 0 ? amount : 0; };
register({ name: 'reg', aliases: ['register'], category: 'economy', description: 'Register an RPG profile', handler: async ctx => { if (!rpgAvailable()) return unavailable(ctx); const user = await ensureUser(ctx.sender); await ctx.sock.sendMessage(ctx.chat, { text: `RPG profile ready. Balance: ${user.balance}` }); } });
register({ name: 'balance', aliases: ['bal'], category: 'economy', description: 'Show RPG balance', handler: async ctx => { if (!rpgAvailable()) return unavailable(ctx); const user = await ensureUser(ctx.sender); await ctx.sock.sendMessage(ctx.chat, { text: `Balance: ${user.balance} coins` }); } });
register({ name: 'rpgprofile', category: 'economy', description: 'Show RPG profile', handler: async ctx => { if (!rpgAvailable()) return unavailable(ctx); const user = await ensureUser(ctx.sender); await ctx.sock.sendMessage(ctx.chat, { text: `RPG Profile\nID: ${user.id}\nBalance: ${user.balance}\nXP: ${user.xp}\nLevel: ${user.level}` }); } });
register({ name: 'daily', category: 'economy', description: 'Claim a daily RPG reward', cooldown: 5, handler: async ctx => { if (!rpgAvailable()) return unavailable(ctx); const user = await ensureUser(ctx.sender); const today = new Date().toISOString().slice(0, 10); if (user.lastDaily === today) return void await ctx.sock.sendMessage(ctx.chat, { text: 'Daily reward already claimed.' }); user.lastDaily = today; user.balance += 100; await saveUser(user); await ctx.sock.sendMessage(ctx.chat, { text: 'Daily reward: 100 coins.' }); } });
register({ name: 'work', category: 'economy', description: 'Work for RPG coins', handler: async ctx => { if (!rpgAvailable()) return unavailable(ctx); const user = await ensureUser(ctx.sender); user.balance += 50; user.xp += 10; await saveUser(user); await ctx.sock.sendMessage(ctx.chat, { text: 'Work complete: 50 coins and 10 XP.' }); } });
register({ name: 'give', aliases: ['pay','transfer'], category: 'economy', description: 'Transfer RPG coins to a mentioned user', usage: '.give @user amount', handler: async ctx => { if (!rpgAvailable()) return unavailable(ctx); const target = ctx.mentions[0]; const amount = numeric(ctx.args.at(-1)); if (!target || !amount || target === ctx.sender) return void await ctx.sock.sendMessage(ctx.chat, { text: 'Usage: .give @user amount' }); const from = await ensureUser(ctx.sender); if (from.balance < amount) return void await ctx.sock.sendMessage(ctx.chat, { text: 'Insufficient balance.' }); const to = await ensureUser(target); from.balance -= amount; to.balance += amount; await saveUser(from); await saveUser(to); await ctx.sock.sendMessage(ctx.chat, { text: `Transferred ${amount} coins.` }); } });
