/**
 * Report Mailer - Sends reports via SMTP email
 * Uses nodemailer for email delivery
 */

const nodemailer = require('nodemailer');
const config = require('../config/config');

// Transporter cache (reuse connection)
let transporter = null;

/**
 * Create or get cached SMTP transporter
 */
function getTransporter() {
  if (transporter) {
    return transporter;
  }
  
  // Validate required config
  if (!config.SMTP_HOST || !config.SMTP_USER) {
    console.error('[ReportMailer] SMTP not configured. Set SMTP_HOST, SMTP_USER, SMTP_PASSWORD');
    return null;
  }
  
  transporter = nodemailer.createTransport({
    host: config.SMTP_HOST,
    port: config.SMTP_PORT || 587,
    secure: config.SMTP_PORT === 465, // true for 465, false for other ports
    auth: {
      user: config.SMTP_USER,
      pass: config.SMTP_PASSWORD || ''
    }
  });
  
  return transporter;
}

/**
 * Generate HTML version of report
 */
function generateHtmlReport(textReport) {
  // Convert text report to HTML
  const lines = textReport.split('\n');
  let html = '';
  
  for (const line of lines) {
    const escaped = line
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
    
    // Preserve formatting with monospace font
    html += `<span style="font-family: monospace; white-space: pre;">${escaped}</span><br>\n`;
  }
  
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { 
      font-family: Arial, sans-serif; 
      background: #f5f5f5; 
      padding: 20px;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 24px;
    }
    .content {
      padding: 30px;
    }
    .report-text {
      font-family: 'Courier New', monospace;
      font-size: 13px;
      line-height: 1.5;
      white-space: pre-wrap;
      background: #f8f9fa;
      padding: 20px;
      border-radius: 4px;
      overflow-x: auto;
    }
    .footer {
      background: #f8f9fa;
      padding: 20px;
      text-align: center;
      font-size: 12px;
      color: #666;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 ${config.BOT_NAME} Daily Report</h1>
    </div>
    <div class="content">
      <div class="report-text">${textReport}</div>
    </div>
    <div class="footer">
      Generated by ${config.BOT_NAME}<br>
      This is an automated report
    </div>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Send report via email
 * @param {string} reportText - Plain text report content
 * @param {string} toEmail - Recipient email address
 * @returns {Promise<object>} Result of send operation
 */
async function send(reportText, toEmail) {
  const mailer = getTransporter();
  
  if (!mailer) {
    return {
      success: false,
      error: 'SMTP not configured'
    };
  }
  
  if (!toEmail) {
    return {
      success: false,
      error: 'No recipient email configured'
    };
  }
  
  const htmlContent = generateHtmlReport(reportText);
  
  const mailOptions = {
    from: `"${config.BOT_NAME}" <${config.SMTP_USER}>`,
    to: toEmail,
    subject: `📊 ${config.BOT_NAME} Daily Report - ${new Date().toLocaleDateString()}`,
    text: reportText,
    html: htmlContent
  };
  
  // Retry logic with exponential backoff
  const maxRetries = 3;
  let lastError = null;
  
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const info = await mailer.sendMail(mailOptions);
      
      console.log(`[ReportMailer] Email sent successfully: ${info.messageId}`);
      
      return {
        success: true,
        messageId: info.messageId,
        accepted: info.accepted,
        rejected: info.rejected
      };
      
    } catch (error) {
      lastError = error;
      console.error(`[ReportMailer] Send attempt ${attempt} failed:`, error.message);
      
      // Don't retry on authentication errors
      if (error.code === 'EAUTH' || error.code === 'EAUTHENTICATION') {
        console.error('[ReportMailer] Authentication failed. Check SMTP credentials.');
        break;
      }
      
      // Wait before retry (exponential backoff)
      if (attempt < maxRetries) {
        const delay = Math.pow(2, attempt) * 1000; // 2s, 4s, 8s
        await new Promise(resolve => setTimeout(resolve, delay));
      }
    }
  }
  
  return {
    success: false,
    error: lastError ? lastError.message : 'Unknown error'
  };
}

/**
 * Send test email to verify SMTP configuration
 * @param {string} toEmail - Test recipient
 * @returns {Promise<object>} Test result
 */
async function sendTest(toEmail) {
  const testReport = `╔═══════════════════════════════════╗
║     📧 SMTP TEST MESSAGE         ║
╚═══════════════════════════════════╝

This is a test email from ${config.BOT_NAME}.

If you received this, your SMTP configuration is working correctly!

🕐 Sent: ${new Date().toLocaleString()}
🤖 Bot: ${config.BOT_NAME}
`;
  
  return send(testReport, toEmail);
}

/**
 * Reset transporter (for reconfiguration)
 */
function resetTransporter() {
  if (transporter) {
    transporter.close();
    transporter = null;
  }
}

module.exports = {
  send,
  sendTest,
  resetTransporter,
  getTransporter
};
