'use strict';

const fs = require('fs');
const path = require('path');

const {
  default: makeWASocket,
  useMultiFileAuthState,
  DisconnectReason,
  Browsers
} = require('@whiskeysockets/baileys');

const { Boom } = require('@hapi/boom');
const pino = require('pino');

const { config } = require('../../config/config.js');
const { log } = require('../../lib/utils/logger.js');

class ConnectionManager {
  constructor(options = {}) {
    this.config = options.config || config;

    this.sock = null;
    this.authState = null;

    this.status = 'disconnected';
    this.user = null;

    this.reconnectTimer = null;
    this.reconnectAttempts = 0;

    this.maxReconnectAttempts =
      Number(this.config.maxReconnectAttempts ?? 10);

    this.isStarting = false;
    this.isStopping = false;

    /*
     * SESSION_ID is restored only once during the
     * initial startup of this process.
     *
     * Reconnects reuse the auth files generated by
     * Baileys instead of decoding SESSION_ID again.
     */
    this.sessionPrepared = false;

    this.startedAt = null;
    this.lastActivity = null;

    this.reconnectStats = {
      attempts: 0,
      successful: 0,
      lastAttempt: null
    };

    this.groups = [];

    this.messageHandler = null;
    this.messageUpdateHandler = null;
    this.callHandler = null;

    this.logger = pino({
      level: process.env.LOG_LEVEL || 'silent'
    });

    /*
     * AUTH_DIR can be changed from environment:
     *
     * AUTH_DIR=./Tanu-htx-session
     *
     * Default:
     * ./auth
     */
    this.authDir = path.resolve(
      process.env.AUTH_DIR || './auth'
    );

    this.ensureAuthDirectory();
  }

  /**
   * Create authentication directory.
   */
  ensureAuthDirectory() {
    if (!fs.existsSync(this.authDir)) {
      fs.mkdirSync(this.authDir, {
        recursive: true,
        mode: 0o700
      });
    }
  }

  /**
   * Completely remove the current local auth state.
   *
   * This is used ONLY during the first startup restore
   * from SESSION_ID.
   *
   * It is NOT used during normal reconnects.
   */
  async resetAuthDirectory() {
    try {
      await fs.promises.rm(this.authDir, {
        recursive: true,
        force: true
      });
    } catch (error) {
      throw new Error(
        `Failed to reset auth directory: ${error.message}`
      );
    }

    await fs.promises.mkdir(this.authDir, {
      recursive: true,
      mode: 0o700
    });
  }

  /**
   * Decode Tanu-XAI~ session.
   *
   * Expected format:
   *
   * Tanu-XAI~<base64-json>
   *
   * Supported payloads:
   *
   * {
   *   version: 1,
   *   creds: {...},
   *   keys: {
   *     "pre-key-1.json": {...},
   *     ...
   *   }
   * }
   *
   * Also supports:
   *
   * {
   *   auth: {
   *     creds: {...},
   *     keys: {...}
   *   }
   * }
   *
   * and:
   *
   * {
   *   session: {
   *     creds: {...},
   *     keys: {...}
   *   }
   * }
   */
  decodeSessionId(sessionId) {
    if (!sessionId) {
      throw new Error('SESSION_ID is empty');
    }

    if (
      typeof sessionId !== 'string' ||
      !sessionId.startsWith('Tanu-XAI~')
    ) {
      throw new Error(
        'SESSION_ID must use Tanu-XAI~ format'
      );
    }

    const encoded = sessionId
      .slice('Tanu-XAI~'.length)
      .trim();

    if (!encoded) {
      throw new Error(
        'SESSION_ID contains no encoded session data'
      );
    }

    let decoded;

    try {
      decoded = Buffer
        .from(encoded, 'base64')
        .toString('utf8');
    } catch {
      throw new Error(
        'SESSION_ID contains invalid base64 data'
      );
    }

    if (!decoded) {
      throw new Error(
        'SESSION_ID decoded to an empty value'
      );
    }

    try {
      return JSON.parse(decoded);
    } catch {
      throw new Error(
        'SESSION_ID decoded successfully but is not valid JSON'
      );
    }
  }

  /**
   * Prepare local Baileys auth state from SESSION_ID.
   *
   * IMPORTANT:
   *
   * This runs only once per process.
   * Reconnects do not call this method again.
   */
  async prepareSession() {
    if (this.sessionPrepared) {
      return;
    }

    if (!this.config.sessionId) {
      throw new Error(
        'SESSION_ID is not configured'
      );
    }

    log.info(
      'WA',
      `Preparing WhatsApp authentication in ${this.authDir}`
    );

    /*
     * SESSION_ID is the source of truth on startup.
     *
     * Remove stale/incomplete auth files before restoring
     * the new session.
     */
    await this.resetAuthDirectory();

    const payload = this.decodeSessionId(
      this.config.sessionId
    );

    /*
     * Complete auth payload:
     *
     * {
     *   creds: {...},
     *   keys: {...}
     * }
     */
    if (
      payload &&
      typeof payload === 'object' &&
      payload.creds &&
      payload.keys
    ) {
      await this.restoreAuthPayload(payload);

      this.sessionPrepared = true;

      log.info(
        'WA',
        'Complete SESSION_ID auth state restored successfully.'
      );

      return;
    }

    /*
     * Wrapped auth payload:
     *
     * {
     *   auth: {
     *     creds: {...},
     *     keys: {...}
     *   }
     * }
     */
    if (
      payload &&
      typeof payload === 'object' &&
      payload.auth &&
      payload.auth.creds &&
      payload.auth.keys
    ) {
      await this.restoreAuthPayload(
        payload.auth
      );

      this.sessionPrepared = true;

      log.info(
        'WA',
        'Wrapped SESSION_ID auth state restored successfully.'
      );

      return;
    }

    /*
     * Wrapped session payload:
     *
     * {
     *   session: {
     *     creds: {...},
     *     keys: {...}
     *   }
     * }
     */
    if (
      payload &&
      typeof payload === 'object' &&
      payload.session &&
      typeof payload.session === 'object'
    ) {
      const session = payload.session;

      if (!session.creds) {
        throw new Error(
          'SESSION_ID session payload is missing creds'
        );
      }

      await this.writeJson(
        path.join(
          this.authDir,
          'creds.json'
        ),
        session.creds
      );

      if (session.keys) {
        await this.restoreKeys(
          session.keys
        );
      }

      this.sessionPrepared = true;

      log.info(
        'WA',
        'Session-wrapped SESSION_ID restored successfully.'
      );

      return;
    }

    /*
     * Creds-only payload.
     *
     * This is supported for compatibility, although
     * a complete creds + keys session is preferred.
     */
    if (
      payload &&
      typeof payload === 'object' &&
      payload.creds
    ) {
      await this.writeJson(
        path.join(
          this.authDir,
          'creds.json'
        ),
        payload.creds
      );

      this.sessionPrepared = true;

      log.warn(
        'WA',
        'SESSION_ID contains creds only. Baileys will generate missing key state.'
      );

      return;
    }

    throw new Error(
      'Unsupported SESSION_ID payload. Expected creds/keys auth state.'
    );
  }

  /**
   * Restore complete Baileys authentication state.
   */
  async restoreAuthPayload(auth) {
    if (
      !auth ||
      typeof auth !== 'object'
    ) {
      throw new Error(
        'Invalid authentication payload'
      );
    }

    if (!auth.creds) {
      throw new Error(
        'Authentication payload is missing creds'
      );
    }

    await this.writeJson(
      path.join(
        this.authDir,
        'creds.json'
      ),
      auth.creds
    );

    if (auth.keys) {
      await this.restoreKeys(
        auth.keys
      );
    }

    /*
     * Verify creds was actually written.
     */
    const credsPath = path.join(
      this.authDir,
      'creds.json'
    );

    if (!fs.existsSync(credsPath)) {
      throw new Error(
        'Failed to create creds.json'
      );
    }
  }

  /**
   * Restore Baileys key files.
   *
   * VERY IMPORTANT:
   *
   * Generator stores keys using their original filenames:
   *
   * pre-key-123.json
   * sender-key-xxx.json
   * app-state-sync-key-xxx.json
   *
   * Therefore we MUST NOT append another ".json".
   */
  async restoreKeys(keys) {
    if (
      !keys ||
      typeof keys !== 'object'
    ) {
      return;
    }

    const keysDir = path.join(
      this.authDir,
      'keys'
    );

    await fs.promises.mkdir(
      keysDir,
      {
        recursive: true,
        mode: 0o700
      }
    );

    /*
     * Compatibility with payloads using:
     *
     * keys: {
     *   files: {
     *     "pre-key-1.json": {...}
     *   }
     * }
     */
    const source =
      keys.files &&
      typeof keys.files === 'object'
        ? keys.files
        : keys;

    for (
      const [fileName, value]
      of Object.entries(source)
    ) {
      if (
        value === undefined ||
        value === null
      ) {
        continue;
      }

      /*
       * Security:
       *
       * Only allow simple JSON filenames.
       * Never allow ../ or nested arbitrary paths.
       */
      const safeName =
        path.basename(fileName);

      if (
        safeName !== fileName ||
        !safeName.endsWith('.json')
      ) {
        log.warn(
          'WA',
          `Skipping invalid Baileys auth key filename: ${fileName}`
        );

        continue;
      }

      await this.writeJson(
        path.join(
          keysDir,
          safeName
        ),
        value
      );
    }
  }

  /**
   * Safely write JSON.
   */
  async writeJson(filePath, value) {
    const directory =
      path.dirname(filePath);

    await fs.promises.mkdir(
      directory,
      {
        recursive: true,
        mode: 0o700
      }
    );

    await fs.promises.writeFile(
      filePath,
      JSON.stringify(
        value,
        null,
        2
      ),
      {
        encoding: 'utf8',
        mode: 0o600
      }
    );
  }

  /**
   * Create Baileys socket.
   */
  async createSocket() {
    if (this.isStopping) {
      return null;
    }

    if (
      this.sock &&
      this.status === 'connected'
    ) {
      log.info(
        'WA',
        'WhatsApp socket already connected.'
      );

      return this.sock;
    }

    if (this.isStarting) {
      log.info(
        'WA',
        'WhatsApp connection is already starting.'
      );

      return this.sock;
    }

    this.isStarting = true;
    this.status = 'connecting';

    this.updateGlobalConnection();

    try {
      this.ensureAuthDirectory();

      /*
       * Restore SESSION_ID only during the first
       * connection attempt of this process.
       *
       * Reconnects reuse the current auth directory.
       */
      if (!this.sessionPrepared) {
        await this.prepareSession();
      }

      const {
        state,
        saveCreds
      } = await useMultiFileAuthState(
        this.authDir
      );

      this.authState = {
        state,
        saveCreds
      };

      /*
       * Baileys browser compatibility.
       */
      const browser =
        Browsers?.ubuntu
          ? Browsers.ubuntu(
              this.config.botName ||
              'Tanu XAI'
            )
          : [
              this.config.botName ||
              'Tanu XAI',
              'Chrome',
              '20.0.04'
            ];

      const sock = makeWASocket({
        auth: state,

        browser,

        logger: this.logger,

        printQRInTerminal: false,

        markOnlineOnConnect: false,

        syncFullHistory: false,

        generateHighQualityLinkPreview: false
      });

      this.sock = sock;

      this.updateGlobalConnection();

      /*
       * Save Baileys credentials whenever they change.
       */
      sock.ev.on(
        'creds.update',
        async () => {
          try {
            await saveCreds();
          } catch (error) {
            log.error(
              'WA',
              `Failed to save credentials: ${error.message}`
            );
          }
        }
      );

      /*
       * Connection state.
       */
      sock.ev.on(
        'connection.update',
        async update => {
          try {
            await this.handleConnectionUpdate(
              update
            );
          } catch (error) {
            log.error(
              'WA',
              `Connection update handler error: ${error.message}`
            );
          }
        }
      );

      /*
       * Incoming messages.
       */
      sock.ev.on(
        'messages.upsert',
        async event => {
          this.lastActivity = Date.now();

          this.updateGlobalConnection();

          if (
            typeof this.messageHandler ===
            'function'
          ) {
            try {
              await this.messageHandler(
                sock,
                event
              );
            } catch (error) {
              log.error(
                'MESSAGE',
                `Message handler error: ${error.message}`
              );
            }
          }
        }
      );

      /*
       * Message updates.
       */
      sock.ev.on(
        'messages.update',
        async updates => {
          if (
            typeof this.messageUpdateHandler ===
            'function'
          ) {
            try {
              await this.messageUpdateHandler(
                sock,
                updates
              );
            } catch (error) {
              log.error(
                'MESSAGE',
                `Message update handler error: ${error.message}`
              );
            }
          }
        }
      );

      /*
       * Incoming calls.
       */
      sock.ev.on(
        'call',
        async callData => {
          if (
            typeof this.callHandler ===
            'function'
          ) {
            try {
              await this.callHandler(
                sock,
                callData
              );
            } catch (error) {
              log.error(
                'CALL',
                `Call handler error: ${error.message}`
              );
            }
          }
        }
      );

      this.isStarting = false;

      this.updateGlobalConnection();

      return sock;
    } catch (error) {
      this.isStarting = false;
      this.status = 'disconnected';

      this.updateGlobalConnection();

      log.error(
        'WA',
        `Failed to create WhatsApp socket: ${error.message}`
      );

      throw error;
    }
  }

  /**
   * Handle Baileys connection.update.
   */
  async handleConnectionUpdate(update) {
    const {
      connection,
      lastDisconnect,
      qr
    } = update;

    /*
     * QR should normally not appear because the bot
     * uses SESSION_ID authentication.
     */
    if (qr) {
      log.warn(
        'WA',
        'WhatsApp QR received. SESSION_ID authentication was expected.'
      );
    }

    if (
      connection === 'connecting'
    ) {
      this.status = 'connecting';

      this.updateGlobalConnection();

      log.info(
        'WA',
        'Connecting to WhatsApp...'
      );

      return;
    }

    if (
      connection === 'open'
    ) {
      this.status = 'connected';

      this.user =
        this.sock?.user || null;

      this.startedAt =
        this.startedAt ||
        Date.now();

      this.lastActivity =
        Date.now();

      this.reconnectAttempts = 0;

      this.reconnectStats.successful += 1;

      this.updateGlobalConnection();

      log.info(
        'WA',
        `WhatsApp connected as ${
          this.user?.id ||
          this.user?.name ||
          'unknown'
        }`
      );

      return;
    }

    if (
      connection !== 'close'
    ) {
      return;
    }

    this.status = 'disconnected';

    this.updateGlobalConnection();

    const statusCode =
      this.getDisconnectStatusCode(
        lastDisconnect
      );

    const disconnectError =
      lastDisconnect?.error;

    const errorMessage =
      disconnectError?.message ||
      'none';

    log.warn(
      'WA',
      `WhatsApp connection closed (code: ${
        statusCode ?? 'unknown'
      }, error: ${errorMessage})`
    );

    /*
     * Log useful diagnostic information without
     * exposing SESSION_ID.
     */
    if (disconnectError) {
      try {
        const details =
          JSON.stringify(
            disconnectError,
            Object.getOwnPropertyNames(
              disconnectError
            )
          );

        log.debug(
          'WA',
          `Disconnect details: ${details}`
        );
      } catch {
        // Ignore diagnostic serialization errors.
      }
    }

    /*
     * Explicit shutdown.
     */
    if (this.isStopping) {
      await this.clearSocket();
      return;
    }

    /*
     * Logged out.
     *
     * Never reconnect automatically.
     */
    if (
      statusCode ===
      DisconnectReason.loggedOut
    ) {
      log.error(
        'WA',
        'WhatsApp session is logged out. Reconnect stopped.'
      );

      await this.clearSocket();

      return;
    }

    /*
     * Bad session.
     *
     * The SESSION_ID/auth state itself is invalid.
     * Do not endlessly retry the same broken session.
     */
    if (
      statusCode ===
      DisconnectReason.badSession
    ) {
      log.error(
        'WA',
        'WhatsApp session is invalid or corrupted. Reconnect stopped.'
      );

      await this.clearSocket();

      return;
    }

    /*
     * Restart required.
     */
    if (
      statusCode ===
      DisconnectReason.restartRequired
    ) {
      await this.scheduleReconnect(
        'restart required',
        true
      );

      return;
    }

    /*
     * Normal temporary failures.
     */
    if (
      statusCode ===
        DisconnectReason.connectionClosed ||
      statusCode ===
        DisconnectReason.connectionLost ||
      statusCode ===
        DisconnectReason.timedOut ||
      statusCode === null ||
      statusCode === undefined
    ) {
      await this.scheduleReconnect(
        'temporary connection failure',
        false
      );

      return;
    }

    /*
     * Any other unknown disconnect:
     * bounded reconnect.
     */
    await this.scheduleReconnect(
      `unknown disconnect (${statusCode})`,
      false
    );
  }

  /**
   * Extract DisconnectReason code.
   */
  getDisconnectStatusCode(
    lastDisconnect
  ) {
    if (!lastDisconnect) {
      return null;
    }

    const error =
      lastDisconnect.error;

    if (!error) {
      return null;
    }

    if (
      error instanceof Boom
    ) {
      return (
        error.output?.statusCode ??
        null
      );
    }

    if (
      error.output?.statusCode
    ) {
      return error.output.statusCode;
    }

    if (
      error.statusCode
    ) {
      return error.statusCode;
    }

    /*
     * Some errors expose the code through data.
     */
    if (
      error.data?.statusCode
    ) {
      return error.data.statusCode;
    }

    return null;
  }

  /**
   * Schedule bounded exponential-backoff reconnect.
   */
  async scheduleReconnect(
    reason,
    immediate = false
  ) {
    if (this.isStopping) {
      return;
    }

    /*
     * Prevent duplicate reconnect timers.
     */
    if (this.reconnectTimer) {
      return;
    }

    if (
      this.reconnectAttempts >=
      this.maxReconnectAttempts
    ) {
      log.error(
        'WA',
        `Maximum reconnect attempts (${this.maxReconnectAttempts}) reached.`
      );

      return;
    }

    this.reconnectAttempts += 1;

    this.reconnectStats.attempts += 1;

    this.reconnectStats.lastAttempt =
      Date.now();

    /*
     * Exponential backoff:
     *
     * #1 = 2s
     * #2 = 4s
     * #3 = 8s
     * #4 = 16s
     * #5 = 32s
     * #6+ = 60s
     */
    const exponentialDelay =
      Math.min(
        60_000,
        2_000 *
          Math.pow(
            2,
            this.reconnectAttempts - 1
          )
      );

    const delayMs =
      immediate
        ? 1_000
        : exponentialDelay;

    log.warn(
      'WA',
      `Reconnect #${this.reconnectAttempts}/${this.maxReconnectAttempts} in ${Math.round(
        delayMs / 1000
      )}s (${reason})`
    );

    this.reconnectTimer =
      setTimeout(
        async () => {
          this.reconnectTimer = null;

          if (this.isStopping) {
            return;
          }

          try {
            await this.clearSocket();

            await this.createSocket();
          } catch (error) {
            log.error(
              'WA',
              `Reconnect attempt failed: ${error.message}`
            );

            /*
             * createSocket() failure does not necessarily
             * generate connection.update, so explicitly
             * schedule another attempt.
             */
            await this.scheduleReconnect(
              'reconnect attempt failed',
              false
            );
          }
        },
        delayMs
      );
  }

  /**
   * Clear current socket listeners/reference.
   *
   * IMPORTANT:
   * Auth files are NOT deleted here.
   */
  async clearSocket() {
    const oldSocket =
      this.sock;

    if (oldSocket) {
      try {
        oldSocket.ev.removeAllListeners();
      } catch {
        // Ignore listener cleanup errors.
      }

      /*
       * Try to close underlying websocket if available.
       */
      try {
        if (
          oldSocket.ws &&
          typeof oldSocket.ws.close ===
            'function'
        ) {
          oldSocket.ws.close();
        }
      } catch {
        // Ignore socket close errors.
      }
    }

    this.sock = null;
    this.authState = null;
    this.user = null;

    this.updateGlobalConnection();
  }

  /**
   * Update global connection information used by
   * existing commands.
   */
  updateGlobalConnection() {
    global.waConnection = {
      socket: this.sock,

      status: this.status,

      user: this.user,

      groups: this.groups,

      lastActivity:
        this.lastActivity,

      reconnectStats: {
        attempts:
          this.reconnectStats.attempts,

        successful:
          this.reconnectStats.successful,

        lastAttempt:
          this.reconnectStats.lastAttempt
      }
    };
  }

  /**
   * Register application message handler.
   */
  setMessageHandler(handler) {
    if (
      handler !== null &&
      typeof handler !== 'function'
    ) {
      throw new TypeError(
        'message handler must be a function or null'
      );
    }

    this.messageHandler =
      handler;
  }

  /**
   * Register messages.update handler.
   */
  setMessageUpdateHandler(handler) {
    if (
      handler !== null &&
      typeof handler !== 'function'
    ) {
      throw new TypeError(
        'message update handler must be a function or null'
      );
    }

    this.messageUpdateHandler =
      handler;
  }

  /**
   * Register call handler.
   */
  setCallHandler(handler) {
    if (
      handler !== null &&
      typeof handler !== 'function'
    ) {
      throw new TypeError(
        'call handler must be a function or null'
      );
    }

    this.callHandler =
      handler;
  }

  /**
   * Get current socket.
   */
  getSocket() {
    return this.sock;
  }

  /**
   * Get connection diagnostics.
   */
  getDiagnostics() {
    return {
      status:
        this.status,

      user:
        this.user,

      socket:
        this.sock
          ? {
              type:
                this.sock.type,

              readyState:
                this.sock.ws?.readyState ??
                this.sock.socket?.readyState ??
                'N/A',

              protocol:
                this.sock.ws?.protocol ??
                this.sock.socket?.protocol ??
                'N/A'
            }
          : null,

      authDir:
        this.authDir,

      sessionPrepared:
        this.sessionPrepared,

      reconnectStats: {
        ...this.reconnectStats
      },

      groups:
        this.groups,

      lastActivity:
        this.lastActivity,

      startedAt:
        this.startedAt
    };
  }

  /**
   * Gracefully shutdown connection manager.
   */
  async shutdown() {
    if (this.isStopping) {
      return;
    }

    this.isStopping = true;

    log.info(
      'SHUTDOWN',
      'Stopping WhatsApp connection manager...'
    );

    if (this.reconnectTimer) {
      clearTimeout(
        this.reconnectTimer
      );

      this.reconnectTimer =
        null;
    }

    const socket =
      this.sock;

    this.sock = null;

    if (socket) {
      try {
        socket.ev.removeAllListeners();
      } catch {
        // Ignore.
      }

      try {
        if (
          socket.ws &&
          typeof socket.ws.close ===
            'function'
        ) {
          socket.ws.close();
        }
      } catch {
        // Ignore close errors.
      }
    }

    this.authState = null;
    this.user = null;
    this.status = 'disconnected';

    this.updateGlobalConnection();

    log.info(
      'SHUTDOWN',
      'WhatsApp connection manager stopped.'
    );
  }
}

/**
 * Factory.
 */
function createConnectionManager(
  options = {}
) {
  return new ConnectionManager(
    options
  );
}

module.exports = {
  ConnectionManager,
  createConnectionManager
};
