import { register } from './handlers/commands.js';
import { showMenu, showOwners } from './handlers/menu.js';
import { getSettings, updateSettings } from './handlers/settings.js';
import { addSudo, removeSudo, listSudo } from './permissions/sudo.js';
import type { CommandContext } from './types.js';
const reply = (text: string | ((ctx: CommandContext) => string)) => async (ctx: CommandContext) => { await ctx.sock.sendMessage(ctx.chat, { text: typeof text === 'function' ? text(ctx) : text }); };
const owner = (name: string, description: string, handler: (ctx: CommandContext) => Promise<void>) => register({ name, category: 'owner', description, ownerOnly: true, handler });
register({ name: 'menu', aliases: ['help'], category: 'tools', description: 'Show category menu', handler: showMenu });
register({ name: 'owners', aliases: ['contact'], category: 'tools', description: 'Show permanent owner cards', handler: showOwners });
register({ name: 'alive', aliases: ['ping'], category: 'tools', description: 'Check bot status', handler: reply('🟢 Tanu XAI is online.') });
register({ name: 'runtime', category: 'tools', description: 'Show uptime', handler: reply(() => `Runtime: ${Math.floor(process.uptime())}s`) });
owner('setsudo', 'Delegate sudo access', async ctx => { const jid = ctx.mentions[0] ?? ctx.args[0] ?? ''; await ctx.sock.sendMessage(ctx.chat, { text: addSudo(jid) ? 'Sudo user added.' : 'Provide a valid non-owner number or mention.' }); });
owner('delsudo', 'Remove sudo access', async ctx => { await ctx.sock.sendMessage(ctx.chat, { text: removeSudo(ctx.mentions[0] ?? ctx.args[0] ?? '') ? 'Sudo user removed.' : 'Sudo user not found.' }); });
owner('getsudo', 'List sudo users', reply(() => `Sudo users: ${listSudo().join(', ') || 'none'}`));
owner('setname', 'Change bot name', async ctx => { const name = ctx.args.join(' ').trim(); if (name) updateSettings({ name }); await ctx.sock.sendMessage(ctx.chat, { text: name ? `Name set to ${name}` : 'Usage: .setname <name>' }); });
owner('setprefix', 'Change prefix', async ctx => { const prefix = ctx.args[0]; if (prefix && prefix.length <= 3) updateSettings({ prefix }); await ctx.sock.sendMessage(ctx.chat, { text: prefix && prefix.length <= 3 ? `Prefix set to ${prefix}` : 'Usage: .setprefix <1-3 chars>' }); });
owner('setmode', 'Set public/private mode', async ctx => { const mode = ctx.args[0] === 'private' ? 'private' : ctx.args[0] === 'public' ? 'public' : ''; if (mode) updateSettings({ mode }); await ctx.sock.sendMessage(ctx.chat, { text: mode ? `Mode set to ${mode}` : 'Usage: .setmode public|private' }); });
owner('settings', 'Show bot settings', reply(() => JSON.stringify(getSettings(), null, 2)));
for (const name of ['setwatermark', 'setpackname', 'setauthor']) owner(name, 'Update bot metadata', async ctx => { const patch = name === 'setwatermark' ? { watermark: ctx.args.join(' ') } : name === 'setpackname' ? { packname: ctx.args.join(' ') } : { author: ctx.args.join(' ') }; updateSettings(patch); await ctx.sock.sendMessage(ctx.chat, { text: 'Setting updated.' }); });
for (const name of ['ai','ask','gpt','translate','summarize']) register({ name, category: 'ai', description: 'AI provider command', handler: reply('AI provider is not configured. Set AI_PROVIDER, AI_API_KEY, and optionally AI_BASE_URL.') });
for (const name of ['song','play','yt','youtube','instagram','insta','tiktok','fb','facebook','pin','pinterest']) register({ name, category: 'download', description: 'Downloader provider command', handler: reply('Downloader provider is not configured.') });
for (const name of ['google','wiki','image']) register({ name, category: 'search', description: 'Search provider command', handler: reply('Search provider is not configured.') });
for (const name of ['sticker','s','enhance','toimage','crop','resize']) register({ name, category: name === 'sticker' || name === 's' ? 'sticker' : 'media', description: 'Media command', handler: reply('Media provider is not configured.') });
