import type { CommandContext, CommandDefinition, Category } from '../types.js';
import { logger } from '../utils/logger.js';
const registry = new Map<string, CommandDefinition>();
const cooldowns = new Map<string, number>();
export function register(command: CommandDefinition) { const normalized = { ...command, usage: command.usage ?? `.${command.name}` }; registry.set(command.name, normalized); for (const alias of command.aliases ?? []) registry.set(alias, normalized); }
export function getCommand(name: string) { return registry.get(name.toLowerCase()); }
export function allCommands() { return [...new Set(registry.values())]; }
export function categoryCommands(category: Category) { return allCommands().filter(command => command.category === category); }
export async function executeCommand(ctx: CommandContext) { const command = getCommand(ctx.command); if (!command) return false; if (command.enabled === false) return void await ctx.sock.sendMessage(ctx.chat, { text: `.${command.name} is currently unavailable; configure its documented provider first.` }); if (command.groupOnly && !ctx.isGroup) return void await ctx.sock.sendMessage(ctx.chat, { text: 'This command is only available in groups.' }); if (command.privateOnly && ctx.isGroup) return void await ctx.sock.sendMessage(ctx.chat, { text: 'This command is only available in private chats.' }); if (command.ownerOnly && !ctx.isOwner) return void await ctx.sock.sendMessage(ctx.chat, { text: 'Owner only command.' }); if (command.adminOnly && !ctx.isAdmin && !ctx.isOwner && !ctx.isSudo) return void await ctx.sock.sendMessage(ctx.chat, { text: 'Group admin permission required.' }); const key = `${ctx.sender}:${command.name}`; const until = cooldowns.get(key) ?? 0; if (until > Date.now()) return void await ctx.sock.sendMessage(ctx.chat, { text: `Please wait ${Math.ceil((until - Date.now()) / 1000)}s.` }); cooldowns.set(key, Date.now() + (command.cooldown ?? 0) * 1000); try { await command.handler(ctx); } catch (error) { logger.error('COMMAND', 'Command failed', { command: command.name, error: error instanceof Error ? error.message : String(error) }); await ctx.sock.sendMessage(ctx.chat, { text: 'That command failed safely. Please try again later.' }); } return true; }
