import type { proto, WASocket } from '@whiskeysockets/baileys';
import { executeCommand } from './commands.js';
import { getSettings } from './settings.js';
import { isOwner } from '../permissions/owner.js';
import { isSudo } from '../permissions/sudo.js';
import { phoneFromJid } from '../config.js';
const textOf = (message: proto.IWebMessageInfo) => message.message?.conversation ?? message.message?.extendedTextMessage?.text ?? message.message?.imageMessage?.caption ?? message.message?.videoMessage?.caption ?? '';
const quotedOf = (message: proto.IWebMessageInfo) => { const quoted = message.message?.extendedTextMessage?.contextInfo?.quotedMessage; return quoted ? ({ message: quoted } as proto.IWebMessageInfo) : undefined; };
export async function handleMessages(upsert: { messages: proto.IWebMessageInfo[]; type: string }, sock: WASocket) { for (const message of upsert.messages) { if (message.key?.fromMe || message.key?.remoteJid === 'status@broadcast' || !message.message) continue; const text = textOf(message).trim(); const prefix = getSettings().prefix; if (!text.startsWith(prefix)) continue; const parts = text.slice(prefix.length).trim().split(/\s+/); const command = (parts.shift() ?? '').toLowerCase(); if (!command) continue; const chat = message.key?.remoteJid ?? ''; const sender = message.key?.participant ?? chat; let isAdmin = false; let isBotAdmin = false; const isGroup = chat.endsWith('@g.us'); if (isGroup) { try { const metadata = await sock.groupMetadata(chat); const participant = metadata.participants.find(item => item.id === sender); const bot = metadata.participants.find(item => item.id === sock.user?.id); isAdmin = Boolean(participant?.admin); isBotAdmin = Boolean(bot?.admin); } catch { /* permissions remain false */ } } await executeCommand({ sock, message, chat, sender, text, args: parts, command, mentions: message.message.extendedTextMessage?.contextInfo?.mentionedJid ?? [], quoted: quotedOf(message), isGroup, isOwner: isOwner(sender), isSudo: isSudo(sender), isAdmin, isBotAdmin }); void phoneFromJid; } }
